# use containers
sudo: false
# cache local R libraries directory:
cache: packages
os:
  - linux
  - osx

r_build_args: --no-build-vignettes --no-manual
env:
  global:
  - R_BUILD_ARGS="--no-build-vignettes --no-manual"
  - R_CHECK_ARGS=" --timings --as-cran"
  - R_CHECK_TIME="TRUE"
  - R_CHECK_TESTS="TRUE"
  - _R_CHECK_TIMINGS_="0"
  - _R_CHECK_FORCE_SUGGESTS_="0"
  - BOOTSTRAP_LATEX=1
  # - WARNINGS_ARE_ERRORS=0  

language: r

r:
  - release
  - devel

matrix:
  allow_failures:
  - os: osx

cran: http://cran.rstudio.com

before_install:
  - export ORIG_PATH=${PATH}    
  - mkdir -p ~/.R
  - export CC=clang
  - export CXX=clang++
  - echo "CC=clang" >  ~/.R/Makevars
  - echo "CXX=clang++" >> ~/.R/Makevars
  - echo "CXX1X=clang++" >> ~/.R/Makevars
  - echo "CXX1XSTD=-std=c++11" >> ~/.R/Makevars
  - source ~/.R/Makevars  
  - wget -O travis_helpers.sh http://bit.ly/travis_helpers
  - source travis_helpers.sh
  - rm travis_helpers.sh
  - export cmake_version="3.4"
  - cmake --version
  - cmake_setup    
  - cmake --version


script:
  - source ~/.R/Makevars
  - cd ..
  - travis_wait 100 R CMD build ITKR ${R_BUILD_ARGS}
  - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1)
  - if [[ ${#TRAVIS_TAG} -eq 0 ]]; then travis_wait 100 R CMD check ${R_CHECK_ARGS} "${PKG_FILE_NAME}" --no-manual --install-args=--build; fi # --as-cran
  - mydir=${PWD}
  - if [[ ${#TRAVIS_TAG} -gt 0 ]]; 
    then 
      travis_wait 100 R CMD INSTALL --build ITKR; 
      PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1); 
    fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ];  
      then  
      PKG_FILE_NAME=$(ls -1t *.tgz | head -n  1);  
    fi

after_success:
  - export PATH=${ORIG_PATH}

after_failure:
  - echo ${TRAVIS_BUILD_DIR}
  - dn=`dirname ${TRAVIS_BUILD_DIR}`
  - cat ${dn}/ITKR.Rcheck/00install.out
  - cat ${dn}/ITKR.Rcheck/00check.log

notifications:
  email:
    recipients:
    - stnava@gmail.com
    on_success: change
    on_failure: always

deploy:
  provider: releases
  api_key:
    secure: UL/OXal9+cvomf7iDtJnAoVY8YEmVa7MECjbBrfnmGeloQ6yRhYVUk5sRlbPNM4VczdtN6/k8hH8LpN/3IT8Wqh+YxIaN0kw/0J05dzj1OLcilRKxTFtQo7i1VYqdTqytXbbvaISaVLF+0UjGIwfFARr/m/GZsKXV54wXhTFirY=
  file: ${PKG_FILE_NAME}
  skip_cleanup: true
  on:
    tags: true
    repo: stnava/ITKR
    all_branches: true
