language: c

compiler:
- clang

os:
- linux
# - osx # currently builds too slowly ...

branches:
  only:
    - master
    - testtar

before_install:
- cd ..
- basedir=${PWD}
- curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
- chmod 755 ./travis-tool.sh
- mkdir -p ~/.R
- export CC=clang
- export CXX=clang++
- echo "CC=clang" >  ~/.R/Makevars
- echo "CXX=clang++" >> ~/.R/Makevars
- source ~/.R/Makevars

install:
- ./travis-tool.sh bootstrap
- wget https://s3.amazonaws.com/rstudio-buildtools/pandoc-1.12.3.zip
- unzip -j pandoc-1.12.3.zip pandoc-1.12.3/linux/debian/x86_64/pandoc
    -d $HOME/pandoc
- chmod +x $HOME/pandoc/pandoc
- export PATH=$PATH:$HOME/pandoc/
- ./travis-tool.sh bootstrap
- ./travis-tool.sh r_binary_install knitr
- cd ${basedir}

script:
- travis_wait 40 R CMD build ITKR
- travis_wait 100 R CMD INSTALL --build ITKR_0.0.tar.gz
- cd ITKR

before_deploy: git fetch --tags

deploy:
  provider: releases
  api_key:
    secure: sMbXZTmLc6h1nsUkZlanuI7huOILHQJSuNLGKRCrmn/NcF6mAW4nX92hSGC1QpXafGAhuzKy0oATVJGVziPWpZ5e4bw3+puPEMfc6w743YMBYYSHoHTGoefnRuzngjDrhSZc7QHSRLp32z3i/cpArLT0SYg61/89h9lp93jXJQo=
  file: ../ITKR_0.0_R_x86_64-pc-linux-gnu.tar.gz

after_failure:
 - ./travis-tool.sh dump_logs

notifications:
  email:
    recipients:
    - stnava@gmail.com
    on_success: change
    on_failure: always

env:
  global:
  - R_BUILD_ARGS=" "
  - R_CHECK_ARGS=" --timings"
  - R_CHECK_TIME="TRUE"
  - R_CHECK_TESTS="TRUE"
  - _R_CHECK_TIMINGS_="0"
  - _R_CHECK_FORCE_SUGGESTS_="0"
  - BOOTSTRAP_LATEX=1
  - WARNINGS_ARE_ERRORS=1
