# use containers
sudo: false

os:
  - linux
  - osx

language: cpp

compiler:
  - clang

matrix:
  allow_failures:
    - os: osx

# only run for pushes to master branch
branches:
  only:
   - master

addons:
  apt:
    sources:
    - r-packages-precise
    packages:
    - cmake
    - r-base-dev
    - r-recommended
    - pandoc

# cache local R libraries directory:
cache:
  directories:
    - ~/Rlib

before_install:
  - basedir=${PWD}
  - cd ..
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then wget --no-check-certificate https://cmake.org/files/v3.4/cmake-3.4.0-rc1-Linux-x86_64.sh; sh cmake-3.4.0-rc1-Linux-x86_64.sh --skip-license --prefix=${HOME}; export PATH=$HOME/bin/:$PATH; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ];  then echo "need cmake 3.2"; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ];  then cmake --version;  curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh ; chmod 755 ./travis-tool.sh;  ./travis-tool.sh bootstrap; fi
  - export PATH=$HOME/bin/:$PATH
  - cd $basedir

# install the package and dependencies:
# - create directory for R libraries (if not already exists)
# - create .Renviron with location of R libraries
# - define R repository in .Rprofile
# - add .travis.yml to .Rbuildignore
# - install devtools if not already installed
# - install covr if not already installed
# - update all installed packages
# - install package with dependencies
install:
  - mkdir -p ~/.R
  - echo "CC=clang" >  ~/.R/Makevars
  - echo "CXX=clang++" >> ~/.R/Makevars
  - echo "CXX1X=clang++" >> ~/.R/Makevars
  - echo "CXX1XSTD=-std=c++11" >> ~/.R/Makevars
  - source ~/.R/Makevars
  - mkdir -p ~/Rlib
  - echo 'R_LIBS=~/Rlib' > .Renviron
  - echo 'R_LIBS_USER="~/Rlib"' >>  $HOME/.Renviron
  - echo 'options(repos = "http://cran.rstudio.com")' > .Rprofile
  - echo '.travis.yml' > .Rbuildignore
  - Rscript -e 'if(!"Rcpp" %in% rownames(installed.packages())) { install.packages("Rcpp", dependencies = TRUE) }'
  - Rscript -e 'if(!"knitr" %in% rownames(installed.packages())) { install.packages("knitr", dependencies = TRUE) }'
#  - Rscript -e 'if(!"devtools" %in% rownames(installed.packages())) { install.packages("devtools", dependencies = TRUE) }'
#  - Rscript -e 'if(!"covr" %in% rownames(installed.packages())) { install.packages("covr", dependencies = TRUE) }'
  - Rscript -e 'update.packages(ask = FALSE, instlib = "~/Rlib")'
  - cd ${basedir}

# Build and check package
script:
  - source ~/.R/Makevars
  - cd ..
#  - travis_wait 100 R CMD build ITKR --no-build-vignettes --no-manual
#  - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1)
#  - travis_wait 100 R CMD check "${PKG_FILE_NAME}" --no-build-vignettes --no-manual # --as-cran
  - travis_wait 100  R CMD INSTALL --build ITKR
  - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1)
  - if [ "$TRAVIS_OS_NAME" == "osx" ];  then  PKG_FILE_NAME=$(ls -1t *.tgz | head -n 1) ; fi

# report coverage rate to coveralls
after_success:
#  - Rscript -e 'covr::coveralls(exclusions = "src/RcppExports.cpp")'

after_failure:
#  - ./travis-tool.sh dump_logs
  - cat /home/travis/build/stnava/ITKR.Rcheck/00install.out
  - cat /home/travis/build/stnava/ITKR.Rcheck/00check.log

# send e-mails if stuff changes
notifications:
  email:
    recipients:
    - stnava@gmail.com
    on_success: change
    on_failure: always

env:
  global:
  - R_BUILD_ARGS=" "
  - R_CHECK_ARGS=" --timings"
  - R_CHECK_TIME="TRUE"
  - R_CHECK_TESTS="TRUE"
  - _R_CHECK_TIMINGS_="0"
  - _R_CHECK_FORCE_SUGGESTS_="0"
  - BOOTSTRAP_LATEX=1
  - WARNINGS_ARE_ERRORS=0

before_deploy:
    - cd $TRAVIS_BUILD_DIR

deploy:
  provider: releases
  api_key:
    secure: ccfe9119010ccc11080d2bf5d37548bef7aab3d7
  file: ${PKG_FILE_NAME}
  skip_cleanup: true
  on:
    branch: master
    repo: stnava/ITKR
