sudo: false
os:
- linux
- osx
language: cpp
compiler:
- clang
matrix:
  allow_failures:
  - os: osx
branches:
  except:
  - /^*-v[0-9]/
addons:
  apt:
    sources:
    - r-packages-precise
    packages:
    - cmake
    - r-base-dev
    - r-recommended
    - pandoc
cache:
  directories:
  - ~/Rlib
before_install:
- basedir=${PWD}
- cd ..
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then wget --no-check-certificate https://cmake.org/files/v3.4/cmake-3.4.0-rc1-Linux-x86_64.sh; sh cmake-3.4.0-rc1-Linux-x86_64.sh --skip-license --prefix=${HOME}; export PATH=$HOME/bin/:$PATH;  fi
- if [ "$TRAVIS_OS_NAME" == "osx" ];  then cmake --version;  curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh;  chmod 755 ./travis-tool.sh;  ./travis-tool.sh bootstrap; fi
- export PATH=$HOME/bin/:$PATH
- cd $basedir
install:
- mkdir -p ~/.R
- echo "CC=clang" >  ~/.R/Makevars
- echo "CXX=clang++" >> ~/.R/Makevars
- echo "CXX1X=clang++" >> ~/.R/Makevars
- echo "CXX1XSTD=-std=c++11" >> ~/.R/Makevars
- source ~/.R/Makevars
- mkdir -p ~/Rlib
- echo 'R_LIBS=~/Rlib' > .Renviron
- echo 'R_LIBS_USER="~/Rlib"' >>  $HOME/.Renviron
- echo 'options(repos = "http://cran.rstudio.com")' > .Rprofile
- echo '.travis.yml' > .Rbuildignore
- Rscript -e 'if(!"Rcpp" %in% rownames(installed.packages())) { install.packages("Rcpp",  dependencies  =  TRUE)  }'
- Rscript -e 'if(!"knitr" %in% rownames(installed.packages())) { install.packages("knitr",  dependencies  = TRUE) }'
- Rscript -e 'update.packages(ask = FALSE, instlib = "~/Rlib")'
- cd ${basedir}
script:
- source ~/.R/Makevars
- cd ..
- travis_wait 100  R CMD INSTALL --build ITKR
- PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1)
- mydir=${PWD}
- if [ "$TRAVIS_OS_NAME" == "osx" ];  then  PKG_FILE_NAME=$(ls -1t *.tgz | head -n  1);  fi
after_failure:
- cat ~/build/stnava/ITKR.Rcheck/00install.out
- cat ~/build/stnava/ITKR.Rcheck/00check.log
notifications:
  email:
    recipients:
    - stnava@gmail.com
    on_success: change
    on_failure: always
env:
  global:
  - R_BUILD_ARGS=" "
  - R_CHECK_ARGS=" --timings"
  - R_CHECK_TIME="TRUE"
  - R_CHECK_TESTS="TRUE"
  - _R_CHECK_TIMINGS_="0"
  - _R_CHECK_FORCE_SUGGESTS_="0"
  - BOOTSTRAP_LATEX=1
  - WARNINGS_ARE_ERRORS=0
  - GH_REF: github.com/stnava/ITKR.git
  - secure: gVr+Jv2MpuBzTeK6D1n9X/LknoVOM3562W827ZR9VVCfdciLs6NCPdhgnEmkZFTbKBxNEL2AVIFDcbKEir5ok+zQXTYxRp/GiwISn0uKCJO4WUqFOEetUiyR8delXhBpV1vvNi3BYHaP6zl3ftMXzARzSecTxA4FyuPkTbOfT9o=
after_success:
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- export GIT_TAG=$TRAVIS_BRANCH-0.1.$TRAVIS_BUILD_NUMBER
- git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
- cd $mydir
- ls $PKG_FILE_NAME

deploy:
  provider: releases
  api_key:
    secure: UL/OXal9+cvomf7iDtJnAoVY8YEmVa7MECjbBrfnmGeloQ6yRhYVUk5sRlbPNM4VczdtN6/k8hH8LpN/3IT8Wqh+YxIaN0kw/0J05dzj1OLcilRKxTFtQo7i1VYqdTqytXbbvaISaVLF+0UjGIwfFARr/m/GZsKXV54wXhTFirY=
  file: ${PKG_FILE_NAME}
  skip_cleanup: true
  on:
    tags: true
    repo: stnava/ITKR
