# ITKR Build
language: r
sudo: false
cache: packages
warnings_are_errors: true
use_bioc: true
bioc_required: true
cran: http://cran.rstudio.com

os:
  - linux
  - osx

r:
  - oldrel  
  - release
  - devel

matrix: 
  allow_failures:
    - r: devel

latex: false
compiler: clang
osx_image: xcode9

env:
  global:
  - R_BUILD_ARGS=" --no-build-vignettes --no-manual"
  - R_CHECK_ARGS=" --timings --as-cran --no-manual --install-args=--build"
  - RGL_USE_NULL=TRUE
  - WARNINGS_ARE_ERRORS=1 
  - DISPLAY=:99.0

before_install:
  - ulimit -n 2048  
  - export LD_LIBRARY_PATH=/usr/local/clang/lib:${LD_LIBRARY_PATH}
  - export PROJ_DIR=`basename $PWD`
  - export ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=1
  - fname=travis_helpers.sh
  - wget -O ${fname} http://bit.ly/travis_helpers
  - cat ${fname}; source ${fname}; rm ${fname}  
  - start_xvfb ;
  - export rver=`r_version`;
  - export gh_user=`get_gh_user` ; echo $gh_user ;
  - cat DESCRIPTION  
  - export PACKAGE_NAME=`package_name`
  - export RCHECK_DIR=${PACKAGE_NAME}.Rcheck  
  # does all the clang exports  
  - x=`export_clang_cxx`; eval ${x}
  - if [ "$TRAVIS_OS_NAME" = "osx" ];
    then
      no_open_mp ; 
    fi  
  - echo "CC=${CC}, CXX=${CXX}, CXX1X=${CXX1X}"
  - echo "CXX1XSTD=${CXX1XSTD}, CXX11=${CXX11}"  
  - clang_cxx  
  - hdf5_install ;
  - export cmake_version="3.11"
  - cmake --version
  - x=`cmake_setup`; echo "${x}"; eval ${x};
  - cmake --version
  - ./cleanup      
  - Rscript -e "install.packages(c('Rcpp', 'RcppEigen'), type = 'source', repos=c(CRAN='https://cran.rstudio.com'))"
  - install_deps_no_suggests

script:
  - x=`export_clang_cxx`; eval ${x}
  - travis_wait 100 R CMD build ${R_BUILD_ARGS} .
  - rm -f travis_wait*.log
  - PKG_TARBALL=$(ls -1t *.tar.gz | head -n 1)  
  - ls
  - travis_wait 100 R CMD check ${R_CHECK_ARGS} "${PKG_TARBALL}"; CHECK_RET=$? ;
  - rm -f travis_wait*.log
  - if [[ $CHECK_RET -ne 0 ]];
    then
      echo "R CMD check failed"; 
      check_fail; 
      dump_logs; 
      check_warnings ;      
      travis_terminate 1;
    fi

after_failure:
  - dump_logs

after_success:
  - dump_logs
  - ls
  - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1);
  - PKG_TARBALL_WITH_R=`echo $PKG_FILE_NAME | sed 's/.tar.gz/_'"R${rver}"'.tar.gz/'` ;
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      PKG_FILE_NAME=$(ls -1t *.tgz | head -n  1);
      PKG_TARBALL_WITH_R=`echo $PKG_FILE_NAME | sed 's/.tgz/_'"R${rver}"'.tgz/'` ;
    fi
  - mv ${PKG_FILE_NAME} ${PKG_TARBALL_WITH_R} ;      
  - PKG_FILE_NAME=${PKG_TARBALL_WITH_R}


notifications:
  email:
    recipients:
    - muschellij2@gmail.com
    - stnava@gmail.com
    on_success: change
    on_failure: always

# so no overwrite of linux build
before_deploy:
  - if [ "$TRAVIS_OS_NAME" = "osx" ];
    then
      rm -f *.tar.gz;
    fi

deploy:
  - provider: releases
    api_key:
      secure: UL/OXal9+cvomf7iDtJnAoVY8YEmVa7MECjbBrfnmGeloQ6yRhYVUk5sRlbPNM4VczdtN6/k8hH8LpN/3IT8Wqh+YxIaN0kw/0J05dzj1OLcilRKxTFtQo7i1VYqdTqytXbbvaISaVLF+0UjGIwfFARr/m/GZsKXV54wXhTFirY=
    file: ${PKG_FILE_NAME}
    skip_cleanup: true
    on:
      tags: true
      repo: ${gh_user}/${PROJ_DIR}
      all_branches: true
      condition: "${gh_user} = stnava"
  - provider: releases
    api_key:
      secure: W21HS1wSxLGv5P4gxasaz7icEmEOphBwwAeWYSl4lzR3uY+K9Lb2tnAuBMYdwGx3P8kSsLTIqS81cncz17BQN0AK16DpFho1TSSp/LO0kHr+tJfJpqWqLl1iPpV5yeiIs9D8jbm1g79EIfEjFVtLh/Wjyagfur7Z48eIbD+o1yhe5jo2TBdtHg77kaHotvURRwM+EhbC7kerdSgOleJ1fUay4/FPftRPyMMjWUbvLjaeo9ZVxlrbaiuSv0FU/PCJYfyN17Y0ZZ8Sqc7iIzq2flsmvk2jAbIVea1yzUZlyPN8FURizvY4T4qiWuN/d2FUzuLQiEJJTKOonJwVsI6FmrQFsHpq7jCDYMnvrTSg2gntpOrZXqnaK1eugQQCOpH+6IEPYlYLA+GZLbRQZrOx6iku/s8vHSPS9+rtiK2GfzbIzfJCqxqYSfj+gu8FfZhBGsN8wam5ZIXkQC1zV43wGT20Wm7q6QIqjhABIz49k4hhp/6AC99nibA9BXc6pTgZxb2r+07iPLGDtQePDIM1LIeuBHPzhCNK7+P7m6iJyhpq2wVxyI4oIj99NKKzvnW6o7oFSTGGEljs5KxZpXI4Xi0Ngu4z/q9mFoNnZY1fSQWTGmSQSae5MfeKJ2V/qjJuDHg3DJ/1UIQR/mROiXBwtLiv5vEg/7S9pnb51Q/3Z5Q=
    file: ${PKG_FILE_NAME}
    skip_cleanup: true
    on:
      tags: true
      repo: ${gh_user}/${PROJ_DIR}
      all_branches: true
      condition: "${gh_user} = muschellij2"
