# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  - ps: Bootstrap

cache:
  - C:\RLibrary

# Adapt as necessary starting from here
build_script:
  - travis-tool.sh install_deps

test_script:
  - set PATH=C:\Rtools\bin;C:\Rtools\MinGW\bin;
  - set PATH=%PATH%;C:\Rtools\mingw_64\bin;
  - set PATH=%PATH%;C:\Program Files\Git\cmd;
  - set PATH=%PATH%;C:\Program Files (x86)\CMake\bin ;
  - set PATH=%PATH%;C:\R\bin\i386;  
  - set PATH=%PATH%;C:\Program Files\Git\usr\bin  
  - set PATH=%PATH%;C:\Users\appveyor\AppData\Roaming\npm
  - set PATH=%PATH%;C:\Users\appveyor\AppData\Local\Yarn\bin
  - set PATH=%PATH%;C:\Program Files\AppVeyor\BuildAgent\
  - travis-tool.sh run_tests


on_failure:
  - appveyor PushArtifact ITKR.Rcheck\00install.out
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
