# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

cache:
  - C:\RLibrary

before_build:
  # - ps: wget 'https://cmake.org/files/v3.9/cmake-3.9.0-rc5-win64-x64.msi'  -OutFile "$pwd\cmake.msi"
  # - ps: msiexec /i cmake.msi /quiet /qn /norestart /log install.log 
  # Workaround for CMake not wanting sh.exe on PATH for MinGW
  # - set PATH=%PATH:C:\Program Files (x86)\Git\bin;=%
  # - set PATH=%PATH:C:\Program Files\Git\bin;=%
  - ren "C:\Program Files\Git\usr\bin\sh.exe" _sh.exe  
  # - ren "C:\Program Files (x86)\Git\usr\bin\sh.exe" _sh.exe  
  # - ps: Get-Command sh.exe -All | Remove-Item

# Adapt as necessary starting from here

build_script:
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
